### ISSUE TITLE
Installation doesn't work with folder outside the container

### ISSUE THREAD

**Issue by gmrizzo** [mkunzmann/docker-fhem#1]
When I install the container with an external volume fhem doesn't start properly because the shared folder is empty.

Do you have a solution for this issue?

**Comment by mkunzmann** [comment]
You might want to try to populate the volume with an FHEM installation or SVN checkout. Then it should start.

**Comment by gmrizzo** [comment]
I downloaded fhem-5.8 [from](https://fhem.de/#Download) and extracted it to the shared folder. But the container restarts everytime. 
This is the error I get:
`INFO exited: fhem (exit status 13; not expected)`                       
` INFO spawned: 'fhem' with pid 15`                                       
` INFO success: fhem entered RUNNING state, process has stayed up for > than 1 seconds (startsecs) `

**Comment by mkunzmann** [comment]
Please check the content of the shared folder. Directly in the folder there should be:
fhem.pl, FHEM subfolder and others.

**Comment by gmrizzo** [comment]
Hey thank you for your support. I don't now why it doesn't work but this is my folder structure.
<img width="700" alt="bildschirmfoto 2018-01-13 um 14 45 01" src="https://user-images.githubusercontent.com/15858721/34906634-51c95dac-f871-11e7-9d0f-2bf241365a4e.png">
Isn't it the correct folder structure? 

In my docker container is this share /path/on/volume:/opt/fhem

**Comment by mkunzmann** [comment]
Looks good. Access rights for everybody set correctly?

When using the container with the external directory on a Synology Diskstation make sure the directory has read/write permission for everyone.

**Comment by gmrizzo** [comment]
Yeah that was my fault. I didn't read the readme completely. Thank you.
