### ISSUE TITLE
PERL WARNING: Can't exec "lsusb"

### ISSUE THREAD

**Issue by CWempe** [mkunzmann/docker-fhem#4]
Not sure if this is worth investing.  
But there is one error I get after starting my little fhem container.

```
PERL WARNING: Can't exec "lsusb": No such file or directory at ./FHEM/98_autocreate.pm line 537.
```

I don't know if this has any impact.
Just wanted to let you know.

**Comment by mkunzmann** [comment]
This is expected and can be ignored unless you directly forward a USB device into the container.
